model\kuaishouId\Entity:
  type: entity
  table: t_kuaishou_id
  id:
    seq:
      type: integer
      options:
        unsigned: true
        comment: '序号'
      generator:
        strategy: AUTO
  fields:
    open_id:
      unique: true
      type: string
      length: 255
      nullable: false
      options:
        fixed: true
        default: ''
        comment: '唯一标识'
    access_token:
      type: string
      length: 500
      nullable: false
      options:
        default: ''
        comment: '接口调用凭证'
    expires_in:
      type: integer
      nullable: false
      options:
        default: '0'
        unsigned: true
        comment: 'access_token接口调用凭证过期时间'
    refresh_token:
      type: string
      length: 500
      nullable: false
      options:
        default: ''
        comment: '用户刷新access_token'
    refresh_token_expires_in:
      type: integer
      nullable: false
      options:
        default: '0'
        unsigned: true
        comment: 'refresh_token凭证过期时间'
    scopes:
      type: json_array
      nullable: false
      options: 
        comment: '本次授权的token包含的scope'
    name:
      type: string
      length: 255
      nullable: false
      options:
        default: ''
        comment: '用户昵称'
    sex:
      type: string
      length: 255
      nullable: false
      options:
        default: ''
        comment: '"M：男性，“F”:女性，其他：未知'
    head:
      type: string
      length: 255
      nullable: false
      options:
        default: ''
        comment: '头像地址'
    bigHead:
      type: string
      length: 255
      nullable: false
      options:
        default: ''
        comment: '大头像地址(可能为空)'
    city:
      type: string
      length: 255
      nullable: false
      options:
        default: ''
        comment: '用户地区名称'
    fan:
      type: string
      length: 255
      nullable: false
      options:
        default: ''
        comment: '粉丝数'
    follow:
      type: string
      length: 255
      nullable: false
      options:
        default: ''
        comment: '关注数'
    disabled:
      type: smallint
      nullable: false
      options:
        default: '0'
        unsigned: true
        comment: '0:启用, 1:禁用'
    create_time:
      type: integer
      nullable: false
      options:
        default: '0'
        unsigned: true
        comment: '添加时间'
    create_ip:
      type: string
      length: 45
      nullable: false
      options:
        fixed: true
        default: ''
        comment: '添加人ip'
    update_time:
      type: integer
      nullable: false
      options:
        default: '0'
        unsigned: true
        comment: '修改时间'
    update_ip:
      type: string
      length: 45
      nullable: false
      options:
        fixed: true
        default: ''
        comment: '修改人ip'
    version:
      type: smallint
      version: true
      options:
        unsigned: true      
        default: '0'