model\sysDbLog\Entity:
  type: entity
  table: t_sys_db_log
  id:
    seq:
      type: integer
      options:
        unsigned: true
        comment: '序号'
      generator:
        strategy: AUTO
  fields:
    type:
      type: string
      length: 1
      nullable: false
      options: 
        fixed: true
        default: ''
        comment: '处理类型，Insert Update Delete'
    table:
      type: string
      length: 45
      nullable: false
      options: 
        default: ''
        comment: '操作的表'
      column: table_name
    uniqid:
      type: string
      length: 255
      nullable: false
      options: 
        default: ''
        comment: '操作数据行的唯一标识'
    data:
      type: json_array
      nullable: true
      options: 
        comment: '所修改的数据信息'
    request:
      type: json_array
      nullable: false
      options: 
        comment: '请求信息'
    create_time:
      type: integer
      nullable: false
      options:
        default: '0'
        unsigned: true
        comment: '添加时间'
    create_user:
      type: string
      length: 32
      nullable: false
      options:
        fixed: true
        default: ''
        comment: '添加人id'
    create_ip:
      type: string
      length: 45
      nullable: false
      options:
        fixed: true
        default: ''
        comment: '添加人ip'